### PR TITLE
Add Keygen logo

### PR DESCRIPTION
**Pull request by ezekg**
We've been a sponsor of @cart for a couple years and saw that the way Bevy accepts donations recently changed. @keygen-sh sponsored at the Diamond tier a couple months back, in addition to our usual @cart sponsorship. This PR adds our logo so that it can be added to the website again on next deployment (or whenever this script is next run).

Of course, the donors file still needs to be updated since I do not know our customer ID.

### CODE REVIEW

**Review by cart — APPROVED** [review]
Sorry for the delay I was on vacation! I've found your customer id. I'll do a followup to add an entry.

**Comment by cart** [comment]
Thanks for your support :heart:

**Comment by ezekg** [comment]
Thanks, @cart! Hope the vacation was good.

**Comment by cart** [comment]
One of the best vacations of my life. Not very restful as I was out dancing until the morning hours almost every day, but I somehow still feel energized from it :)

**Pull request merged**
